domain_path: /home/tamamo/Documents/ENE331_workspace/ENE331-Embedded/Vitis/XADC_Demo_Z7S/zynq_fsbl/zynq_fsbl_bsp
app_src_dir: /usr/local/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/zynq_fsbl
template: zynq_fsbl
