domain_path: /home/tamamo/Documents/ENE331_workspace/ENE331-Embedded/Vitis/metronome_test_1/export/metronome_test_1/sw/standalone_ps7_cortexa9_0
app_src_dir: /usr/local/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
