domain_path: /home/tamamo/Documents/ENE331_workspace/ENE331-Embedded/Vitis/XADC_Demo_Z7S/export/XADC_Demo_Z7S/sw/standalone_ps7_cortexa9_0
app_src_dir: /usr/local/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
